language: cpp

os :
  - linux
  - osx

sudo: required

compiler:
  - gcc
  - clang

jdk:
  - openjdk8
  - oraclejdk8

matrix:
  include:
    - java: openjdk8
      python: "3.4"
      env: TEST_PYTHON=1 JDK_VERSION="openjdk8" PYTHON_VERSION="python3.4"
    - java: oraclejdk8
      env: TEST_PYTHON=1 TEST_JAVA=1 BUILD_ARGS="-DJAVA=ON" JDK_VERSION="oraclejdk8" PYTHON_VERSION="python3.4"
      python: "3.4"
    - java: openjdk9
      python: "3.4"
      env: TEST_PYTHON=1 TEST_JAVA=1 BUILD_ARGS="-DJAVA=ON -DGPL=OFF" JDK_VERSION="openjdk9" PYTHON_VERSION="python3.4"
      os: linux
      dist: trusty
      compiler: clang
    - java: openjdk9
      python: "3.6"
      os: osx
      compiler: clang
      # python doesn't seem to be installing correctly in travis on osx.
      env: TEST_PYTHON=1 TEST_JAVA=1 BUILD_ARGS="-DJAVA=ON -DGPL=OFF" JDK_VERSION="openjdk9" PYTHON_VERSION="python3.6"
  allow_failures:
    - java: openjdk8
      python: "3.4"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - TEST_PYTHON=1 TEST_JAVA=1 BUILD_ARGS="-DJAVA=ON" MATRIX_EVAL="CC=gcc-5 && CXX=g++-5" JDK_VERSION="oraclejdk9" PYTHON_VERSION="python3.4"

    - java: openjdk8
      python: "3.4"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - TEST_PYTHON=1 TEST_JAVA=1 BUILD_ARGS="-DJAVA=ON -DGPL=OFF" MATRIX_EVAL="CC=gcc-7 && CXX=g++-7" JDK_VERSION="openjdk8" PYTHON_VERSION="python3.4"

before_install:
  - echo "os is ${TRAVIS_OS_NAME}"
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then brew update; brew install python3 || brew outdated python3 || brew upgrade python3 ; fi
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then sudo apt-get -qq update; fi
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then sudo apt-get install -y --force-yes cmake libgmp-dev zlib1g-dev; fi
  - eval "${MATRIX_EVAL}"
  - echo "Selected Java ${JDK_VERSION}"  || true
  - jdk_switcher use ${JDK_VERSION}  || true
  - java -version  || true
  - echo "Selected Python ${PYTHON_VERSION}"
  - python3 --version || true

install:
  - cmake ${BUILD_ARGS} .
  - make
  - sudo make install

script:
 - ROOT=$PWD
 - if [[ "$TEST_PYTHON" -eq "1" ]]; then echo "Running python tests" && cd ${ROOT}/src/monosat/api/python/ && sudo python3 setup.py -q install && python3 -m unittest discover && echo "Completed python tests"; fi
 - if [[ "$TEST_JAVA" -eq "1" ]]; then echo "Running java tests" &&  cd ${ROOT}/src/monosat/api/java/tests && javac -cp ".:${ROOT}/monosat.jar:junit-4.12.jar:hamcrest-core-1.3.jar" monosat/*.java && java -Djava.library.path=${ROOT} -cp ".:${ROOT}/monosat.jar:junit-4.12.jar:hamcrest-core-1.3.jar" org.junit.runner.JUnitCore  monosat.TestSuite && echo "Completed java tests"; fi

